set(QStm_SRCS
    ../private/p_qstm_base_setting.cpp
    ../private/p_qstm_base_setting.h
    ../private/p_qstm_result_info.cpp
    ../private/p_qstm_result_info.h
    ../private/p_qstm_setting_manager.cpp
    ../private/p_qstm_setting_manager.h
    ../private/p_qstm_startup.cpp
    ../private/p_qstm_startup.h
    ../qstm.h
    ../qstm_cache_pool.cpp
    ../qstm_cache_pool.h
    ../qstm_const.h
    ../qstm_crypto_util.cpp
    ../qstm_crypto_util.h
    ../qstm_currency.cpp
    ../qstm_currency.h
    ../qstm_fileinfo.cpp
    ../qstm_fileinfo.h
    ../qstm_global.h
    ../qstm_log.cpp
    ../qstm_log.h
    ../qstm_logger.cpp
    ../qstm_logger.h
    ../qstm_macro.h
    ../qstm_message.cpp
    ../qstm_message.h
    ../qstm_meta_enum.h
    ../qstm_meta_types.cpp
    ../qstm_meta_types.h
    ../qstm_network_types.cpp
    ../qstm_network_types.h
    ../qstm_object.cpp
    ../qstm_object.h
    ../qstm_object_wrapper.cpp
    ../qstm_object_wrapper.h
    ../qstm_result.cpp
    ../qstm_result.h
    ../qstm_result_info.cpp
    ../qstm_result_info.h
    ../qstm_setting_base.cpp
    ../qstm_setting_base.h
    ../qstm_setting_manager.cpp
    ../qstm_setting_manager.h
    ../qstm_startup.cpp
    ../qstm_startup.h
    ../qstm_types.cpp
    ../qstm_types.h
    ../qstm_types_const.h
    ../qstm_url.cpp
    ../qstm_url.h
    ../qstm_util_date.cpp
    ../qstm_util_date.h
    ../qstm_util_double.cpp
    ../qstm_util_double.h
    ../qstm_util_formatting.cpp
    ../qstm_util_formatting.h
    ../qstm_util_meta_object.cpp
    ../qstm_util_meta_object.h
    ../qstm_util_path.cpp
    ../qstm_util_path.h
    ../qstm_util_variant.cpp
    ../qstm_util_variant.h
    ../qstm_vvm.cpp
    ../qstm_vvm.h
)
